---
- name: "Install NGINX Perl Module"
  package:
    name: mod-http-perl
    state: present

# - name: "(Setup: All NGINX) Load NGINX Perl Module"
#   lineinfile:
#     path: /etc/nginx/nginx.conf
#     insertbefore: BOF
#     line: load_module modules/ngx_http_perl_module.so;
#   notify: "(Handler: All OSs) Reload NGINX"
