---
- name: "Install NGINX Image Filter Module"
  package:
    name: nginx-mod-http-image-filter
    state: present

# - name: "(Setup: All NGINX) Load NGINX Image Filter Module"
#   lineinfile:
#     path: /etc/nginx/nginx.conf
#     insertbefore: BOF
#     line: load_module modules/ngx_http_image_filter_module.so;
#   notify: "(Handler: All OSs) Reload NGINX"
