---
- name: "Install NGINX Stream Module"
  yum:
    name: nginx-mod-stream
    state: present

# - name: "(Setup: All NGINX) Load NGINX GeoIP Module"
#   blockinfile:
#     path: /etc/nginx/nginx.conf
#     insertbefore: BOF
#     block: |
#       load_module modules/ngx_http_geoip_module.so;
#       load_module modules/ngx_stream_geoip_module.so;
#   notify: restart nginx
