---
language: python
<<<<<<< HEAD

=======
python:
  - "2.7"
>>>>>>> a8d36feb5a74113b306d1e9848275bb40ff56919
services: docker

env:
  - distro: centos7

script:
  # Download test shim.
  # - mkdir -p ${PWD}/tests
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
