---
- name: check registered the repository of nginx-release
  shell: rpm -qa | grep nginx-release
  register: result
  ignore_errors: true
#   always_run: true
  changed_when: false
- name: add repository nginx-release (CentOS6/CentOS7)
  yum: name="http://nginx.org/packages/centos/{{ansible_distribution_major_version}}/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm"
  when: result|failed

# - name: disable the repository (pls set --enablerepo=nginx if you use it)
#   replace: dest=/etc/yum.repos.d/nginx.repo regexp="enabled *= *1" replace="enabled=0"
#   ignore_errors: True

- name: install nginx
  yum: name=nginx state=present enablerepo=nginx
  notify:
    - start nginx

- include: modules/install-geoip.yml
- include: modules/install-image-filter.yml
- include: modules/install-perl.yml
- include: modules/install-stream.yml
- include: modules/install-njs.yml
- include: modules/install-virtualmin.yml
- include: modules/install-virtualmin-ssl.yml

- name: Restart nginx
  notify:
    - restart nginx
# - name: Start Nginx
#   service: name=nginx enabled=yes state=started
